# Seed

In [2]:
import numpy as np
np.random.seed(20)
np.random.rand(4)

array([0.5881308 , 0.89771373, 0.89153073, 0.81583748])

# Brodcasting

In [4]:
import numpy as np
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr/10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [6]:
list1=[1,2,3,4,5,6,7,8,9]
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
list1[2]/10

0.3

In [8]:
arr*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [9]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [10]:
arr[arr>5]

array([6, 7, 8, 9])

In [11]:
list1[list1>5]

TypeError: '>' not supported between instances of 'list' and 'int'

In [12]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr[:]=555
arr

array([555, 555, 555, 555, 555, 555, 555, 555, 555, 555])

In [17]:
 arr2=arr.copy()
arr2

array([555, 555, 555, 555, 555, 555, 555, 555, 555, 555])

In [18]:
arr1=arr[:6]
arr1

array([555, 555, 555, 555, 555, 555])

# Python List Vs Numpy Array

In [37]:
size=1000
x=range(size)
y=range(size)


In [38]:
%%timeit
[x[i]*y[i] for i in range(size)]

251 µs ± 5.51 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [39]:
x1=np.arange(size)
y1=np.arange(size)
%%timeit
x1*y1

UsageError: Line magic function `%%timeit` not found.


# Insert

In [ ]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

In [26]:
b1=np.insert(b,1,[15,16,17],axis=0)

In [28]:
np.insert(b,1,[15,16,17],axis=1)

array([[ 1, 15,  2,  3],
       [ 4, 16,  5,  6],
       [ 7, 17,  8,  9]])

In [29]:
b1

array([[ 1,  2,  3],
       [15, 16, 17],
       [ 4,  5,  6],
       [ 7,  8,  9]])

# Matrix

In [31]:
x=np.matrix('1,2,3;4,5,6;7,8,9')
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [33]:
x[2,1]=-7

In [34]:
x

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7, -7,  9]])

In [40]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [41]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr[2,1]=-7

In [45]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, -7,  9]])

In [46]:
np.insert(arr,2,2)

array([ 1,  2,  2,  3,  4,  5,  6,  7, -7,  9])

In [49]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 49, 81]])

In [50]:
x

range(0, 1000)

In [51]:
arr@arr

array([[ 30,  -9,  42],
       [ 66,  -9,  96],
       [ 42, -84,  60]])

# Storage in file

In [52]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, -7,  9]])

In [54]:
np.savetxt('Python.txt',arr)

In [58]:
np.savetxt('Python.txt',arr,delimiter=',')

In [59]:
np.loadtxt('Python.txt',delimiter=',')

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7., -7.,  9.]])

In [61]:
np.save('data.npy',arr)

In [62]:
np.load('data.npy')

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, -7,  9]])

In [64]:
a=np.arange(10)

In [65]:
np.savez('both.npz',arr,a)

In [66]:
z=np.load('both.npz')

In [67]:
z.files

['arr_0', 'arr_1']

In [68]:
z[z.files[0]]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, -7,  9]])

In [69]:
z[z.files[1]]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Pandas

In [70]:
import pandas as pd
import numpy as np

# Using list

In [71]:
my_list=[100,200,300,400,500]

In [ ]:
 x=pd.Series(my_list,index=['A','B','C','D','E'])
x

In [73]:
type(x)

pandas.core.series.Series

# Using Numpy Array

In [74]:
arr=np.array(my_list)
arr

array([100, 200, 300, 400, 500])

In [75]:
'A B C D E'.split()

['A', 'B', 'C', 'D', 'E']

In [76]:
pd.Series(arr,'A B C D E'.split())

A    100
B    200
C    300
D    400
E    500
dtype: int32

### Using Dictionaries

In [77]:
dict1={'A':100,'B':200,'C':300}


In [87]:
z1=pd.Series(dict1)
z1

A    100
B    200
C    300
dtype: int64

In [88]:
z2=pd.Series([10,20,30,40],'A B C D'.split())

In [89]:
z2

A    10
B    20
C    30
D    40
dtype: int64

In [90]:
z1+z2

A    110.0
B    220.0
C    330.0
D      NaN
dtype: float64

# Slicing in Series

In [91]:
z2[0:2]

A    10
B    20
dtype: int64

In [92]:
z2['A':'C']

A    10
B    20
C    30
dtype: int64

# .Ioc & .iloc Functions

In [93]:
z2.loc['A':'C']

A    10
B    20
C    30
dtype: int64

In [94]:
z2.iloc[0:3]

A    10
B    20
C    30
dtype: int64

In [95]:
z=pd.Series({100:'a',200:'b',300:'c'})
z

100    a
200    b
300    c
dtype: object

In [102]:
z[0]

KeyError: 0

In [103]:
z.iloc[0]

'a'

In [105]:
z.loc[200]

'b'

# Operation

In [106]:
z1

A    100
B    200
C    300
dtype: int64

In [107]:
z1>100

A    False
B     True
C     True
dtype: bool

In [108]:
z1<100

A    False
B    False
C    False
dtype: bool

# Brodcasting

In [109]:
z1+50

A    150
B    250
C    350
dtype: int64

# Ordering

In [110]:
z2

A    10
B    20
C    30
D    40
dtype: int64

In [112]:
z2.sort_values(ascending=False)

D    40
C    30
B    20
A    10
dtype: int64

In [113]:
z2.sort_values(ascending=True)

A    10
B    20
C    30
D    40
dtype: int64

In [115]:
z2.sort_values(ascending=False,inplace=True)

z2

In [116]:
z2

D    40
C    30
B    20
A    10
dtype: int64

# Aggregation on Series

In [117]:
z2

D    40
C    30
B    20
A    10
dtype: int64

In [118]:
z2.min()

10

In [119]:
z2.max()

40

z2.idxmax()

In [123]:
z2.idxmax()

'D'

In [124]:
z2.idxmin()

'A'

# DataFrame

In [125]:
rand_mat=np.random.randn(5,4)

In [126]:
rand_mat

array([[ 0.35753652, -2.34326191, -1.08483259,  0.55969629],
       [ 0.93946935, -0.97848104,  0.50309684,  0.40641447],
       [ 0.32346101, -0.49341088, -0.79201679, -0.84236793],
       [-1.27950266,  0.24571517, -0.0441948 ,  1.56763255],
       [ 1.05110868,  0.40636843, -0.1686461 , -3.18970279]])

In [129]:
df=pd.DataFrame(data=rand_mat,index='A B C D E'.split(),columns='W X Y Z'.split())
df

W         X         Y         Z
A  0.357537 -2.343262 -1.084833  0.559696
B  0.939469 -0.978481  0.503097  0.406414
C  0.323461 -0.493411 -0.792017 -0.842368
D -1.279503  0.245715 -0.044195  1.567633
E  1.051109  0.406368 -0.168646 -3.189703

In [130]:
type(df)

pandas.core.frame.DataFrame

In [131]:
df['W']

A    0.357537
B    0.939469
C    0.323461
D   -1.279503
E    1.051109
Name: W, dtype: float64

In [132]:
type(df['W'])

pandas.core.series.Series

# Selection and Indexing

In [133]:
df.loc['A']

W    0.357537
X   -2.343262
Y   -1.084833
Z    0.559696
Name: A, dtype: float64

In [137]:
df['W']

A    0.357537
B    0.939469
C    0.323461
D   -1.279503
E    1.051109
Name: W, dtype: float64

In [138]:
df[['W','Z']]

W         Z
A  0.357537  0.559696
B  0.939469  0.406414
C  0.323461 -0.842368
D -1.279503  1.567633
E  1.051109 -3.189703

# Add new Column

In [139]:
df['New']=df['W']+df['Y']

In [140]:
df

W         X         Y         Z       New
A  0.357537 -2.343262 -1.084833  0.559696 -0.727296
B  0.939469 -0.978481  0.503097  0.406414  1.442566
C  0.323461 -0.493411 -0.792017 -0.842368 -0.468556
D -1.279503  0.245715 -0.044195  1.567633 -1.323697
E  1.051109  0.406368 -0.168646 -3.189703  0.882463

In [141]:
df.drop('New',axis=1)

W         X         Y         Z
A  0.357537 -2.343262 -1.084833  0.559696
B  0.939469 -0.978481  0.503097  0.406414
C  0.323461 -0.493411 -0.792017 -0.842368
D -1.279503  0.245715 -0.044195  1.567633
E  1.051109  0.406368 -0.168646 -3.189703

In [142]:
df

W         X         Y         Z       New
A  0.357537 -2.343262 -1.084833  0.559696 -0.727296
B  0.939469 -0.978481  0.503097  0.406414  1.442566
C  0.323461 -0.493411 -0.792017 -0.842368 -0.468556
D -1.279503  0.245715 -0.044195  1.567633 -1.323697
E  1.051109  0.406368 -0.168646 -3.189703  0.882463

In [144]:
df.drop('New',axis=1,inplace=True)

In [145]:
df

W         X         Y         Z
A  0.357537 -2.343262 -1.084833  0.559696
B  0.939469 -0.978481  0.503097  0.406414
C  0.323461 -0.493411 -0.792017 -0.842368
D -1.279503  0.245715 -0.044195  1.567633
E  1.051109  0.406368 -0.168646 -3.189703

# Add new Row

In [146]:
df.loc['F']=df.loc['A']+df.loc['C']

In [147]:
df

W         X         Y         Z
A  0.357537 -2.343262 -1.084833  0.559696
B  0.939469 -0.978481  0.503097  0.406414
C  0.323461 -0.493411 -0.792017 -0.842368
D -1.279503  0.245715 -0.044195  1.567633
E  1.051109  0.406368 -0.168646 -3.189703
F  0.680998 -2.836673 -1.876849 -0.282672

In [148]:
df.drop('F',axis=0,inplace=True)

In [149]:
df

W         X         Y         Z
A  0.357537 -2.343262 -1.084833  0.559696
B  0.939469 -0.978481  0.503097  0.406414
C  0.323461 -0.493411 -0.792017 -0.842368
D -1.279503  0.245715 -0.044195  1.567633
E  1.051109  0.406368 -0.168646 -3.189703

In [150]:
df['X']['C']

-0.4934108819088803

In [155]:
df.loc['C']['X']

-0.4934108819088803

# Date Input & Output

In [164]:
pd.read_csv('C:/Users/studio/Downloads/example.csv')

Industry
0              Accounting/Finance
1    Advertising/Public Relations
2              Aerospace/Aviation
3   Arts/Entertainment/Publishing
4                      Automotive
5                Banking/Mortgage
6            Business Development
7            Business Opportunity
8         Clerical/Administrative
9         Construction/Facilities
10                 Consumer Goods
11               Customer Service
12             Education/Training
13               Energy/Utilities
14                    Engineering
15            Government/Military
16                          Green
17                     Healthcare
18             Hospitality/Travel
19                Human Resources
20       Installation/Maintenance
21                      Insurance
22                       Internet
23                Job Search Aids
24       Law Enforcement/Security
25                          Legal
26           Management/Executive
27       Manufacturing/Operations
28                      Marketing
29           Non-Profit/Volunteer
30         Pharmaceutical/Biotech
31          Professional Services
32             QA/Quality Control
33                    Real Estate
34        Restaurant/Food Service
35                         Retail
36                          Sales
37               Science/Research
38                  Skilled Labor
39                     Technology
40             Telecommunications
41       Transportation/Logistics
42                          Other

# Statistics Function

In [165]:
x=np.array([[1,2,3],[4,5,6],[90,50,200]])


In [166]:
x

array([[  1,   2,   3],
       [  4,   5,   6],
       [ 90,  50, 200]])

In [167]:
np.amin(x)

1

In [168]:
np.amax(x)

200

In [169]:
np.amin(x,axis=1)

array([ 1,  4, 50])

In [170]:
np.amin(x,axis=0)

array([1, 2, 3])

In [171]:
np.amax(x,axis=0)

array([ 90,  50, 200])

In [172]:
np.amax(x,axis=1)

array([  3,   6, 200])

In [173]:
x

array([[  1,   2,   3],
       [  4,   5,   6],
       [ 90,  50, 200]])

In [174]:
np.average(x)

40.111111111111114

# Weighted Average

In [175]:
w=[1,2,3]

In [177]:
np.average(x,weights=w,axis=0)

array([ 46.5,  27. , 102.5])

In [178]:
np.average(x,weights=w,axis=1)

array([  2.33333333,   5.33333333, 131.66666667])

In [179]:
np.mean(x)

40.111111111111114

In [180]:
np.mean(x[0])

2.0

In [181]:
np.mean(x[1])

5.0

In [182]:
np.mean(x,axis=0)

array([31.66666667, 19.        , 69.66666667])

In [183]:
np.mean(x,axis=1)

array([  2.        ,   5.        , 113.33333333])

In [185]:
np.median(x)

5.0

In [186]:
np.median(x,axis=1)

array([ 2.,  5., 90.])

In [187]:
np.median(x,axis=0)

array([4., 5., 6.])

In [188]:
np.var(x)

4023.4320987654323

In [189]:
np.std(x)

63.43052970585562